version: "3"
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
#    ports:
#      - "8080:8080"    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net:

