#!/bin/bash
export IMAGE=$(sed -n '1p' /home/remote_user/maven/.auth)
export TAG=$(sed -n '2p' /home/remote_user/maven/.auth)
export PASS=$(sed -n '3p' /home/remote_user/maven/.auth)

docket login -u ravikant1710 -p $PASS
mkdir ~ /maven
cd ~/maven && docker-compose up -d
